apiVersion: v1
kind: Namespace
metadata:
  name: ${K8S_NAMESPACE}

---
apiVersion: v1
kind: Service
metadata:
  name: uleash-porxy-service
  namespace: ${K8S_NAMESPACE}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
      protocol: TCP
  type: NodePort
  selector:
    app: uleash-proxy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uleash-proxy-app
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uleash-proxy
  template:
    metadata:
      labels:
        app: uleash-proxy
    spec:
      containers:
        - name: uleash-proxy
          image: docker.io/unleashorg/unleash-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: UNLEASH_API_TOKEN
              value: [Your_token_key]
            - name: UNLEASH_URL
              value: [uleash_url]
            - name: UNLEASH_PROJECT_NAME
              value: [project_name]
            - name: UNLEASH_PROXY_CLIENT_KEYS
              value: [your client]
            - name: UNLEASH_ENVIRONMENT
              value: deployment
